exclude certain repos
skos-ninja/github-releaser pull request #13
Opened 2021-11-30 17:46 UTC by TheCapedBaldi

# Summary
Before handling the webhook, we validate the URL of the repo against the exclude slice.

2021-12-03 15:19 UTC, tl-NASEEBULLAH-AHMADI commented
@skos-ninja Can I please get a review 😄 

@tl-romain-diegoni FYI 😉

2021-12-06 14:58 UTC, skos-ninja requested changes
Overall it looks good just need to change where we pass in the excluded repos to match the rest of the code

2021-12-06 14:58 UTC, skos-ninja commented on Dockerfile
> +ENTRYPOINT ["./main", "--excluderepos", "TrueLayer/prisma-tbd"]
Please remove this

2021-12-06 14:58 UTC, skos-ninja commented on README.md
> +Once exposed, the webhook receiver URL (which is set in your Github App) needs to point towards the docker image.
```suggestion
Once exposed, the webhook receiver URL (which is set in your Github App) needs to point towards the running docker container.
```

2021-12-06 14:58 UTC, skos-ninja commented on README.md
> +$ go build -a -installsuffix cgo -o main *.go &&& ./main
For running locally it's easier to just do a run rather than a build every time
```suggestion
$ go run *.go
```

2021-12-06 14:58 UTC, skos-ninja commented on README.md
> +**Note:** If you want to test by creating PR in your testing repo, you first have to make sure that the app is installed and accessible by ![your repo](assets/app_installed.png).
This section doesn't quite make sense with the images in it. May be worth rewording the sentences and then providing the images as examples

2021-12-06 14:58 UTC, skos-ninja commented on config.go
> +	. "github.com/skos-ninja/github-releaser/pkg/common"
We normally don't use aliased imports unless absolutely required so as such the `.` should be removed and all uses updated accordingly

2021-12-06 14:58 UTC, skos-ninja commented on config.go
> +		ExcludeRepos:    []string{""},
This should just be an empty array rather than include a blank string

2021-12-06 14:58 UTC, skos-ninja commented on main.go
> +	})
This should go back to being:
```suggestion
	router.POST("/webhooks", rpc.Webhooks)
```
and instead you pass in `cfg.ExcludeRepos` into the `rpc.New` function and add it to that struct

2021-12-06 14:58 UTC, skos-ninja commented on rpc/rpc.go
> +	Webhooks(ctx *gin.Context, excludeRepos []string)
```suggestion
	Webhooks(ctx *gin.Context)
```

2021-12-06 14:58 UTC, skos-ninja commented on rpc/webhooks.go
> +}
```suggestion
func arrayContains(arr []string, str string) bool {
	for _, a := range are {
	       if a == str {
	              return true
	       }
	}

	return false
}
```

2021-12-06 15:01 UTC, skos-ninja commented on rpc/webhooks.go
> +}
If you want to be extra safe with this one it may be worth `strings.ToLower`(ing) them both

2021-12-14 16:45 UTC, merged